### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by amcalgates** [SocketMobile/swift-package-capturesdk#14]
Hi,

Is this SDK updated with a privacy manifest/exempt from one?

> From Fall 2023 you’ll receive an email from Apple if you upload an app to App Store Connect that uses required reason API without describing the reason in its privacy manifest file. From Spring 2024, apps that don’t describe their use of required reason API in their privacy manifest file won’t be accepted by App Store Connect.

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

**Comment by cyrille-socket** [comment]
Yes it has a privacy manifest but empty. So it could be exempt but we put it anyways
