### ISSUE TITLE
The signing certificate has been revoked

### ISSUE THREAD

**Issue by chbeer** [SocketMobile/swift-package-capturesdk#17]
Showing All Errors Only
…/SourcePackages/checkouts/swift-package-capturesdk/Sources/CaptureSDK.xcframework:1:1: The signing certificate has been revoked (CSSMERR_TP_CERT_REVOKED)

<img width="474" alt="image" src="https://github.com/SocketMobile/swift-package-capturesdk/assets/121761/6028bacf-8691-4570-8ca6-869c3625b5ef">

**Comment by cyrille-socket** [comment]
Hi @chbeer,

indeed our certificate has expired so you need to use the latest version of the SDK through our [Developer Portal](https://www.socketmobile.com/developers/portal)
