### ISSUE TITLE
Please provide link what to use after deprecation!

### ISSUE THREAD

**Issue by chbeer** [SocketMobile/swift-package-capturesdk#18]
Your page now shows "THIS REPOSITORY IS NOW DEPRECATED"... but without any hints what to use instead.

**Comment by cyrille-socket** [comment]
Hi @chbeer,

it is written in the first lines of the readme:
"The repository has been relocated within the Socket Mobile developer portal to enhance camera scanning capabilities with the SocketCam C860."

Then the developer portal link is clickable a bit below.

**Comment by chbeer** [comment]
I didn't even read any of the text below the fat headline. If you have such a huge headline, why not have "klick here" directly below it?
