### ISSUE TITLE
Not support Bitcode 

### ISSUE THREAD

**Issue by iLabsJason** [SocketMobile/swift-package-capturesdk#3]
It does not support Bitcode now, I have to set `enable Bitcode` to false in my project. Can we update the SDK to enable Bitcode?

**Comment by cyrille-socket** [comment]
Hi @iLabsJason indeed it's not supported at the moment. We're figuring it out at the moment and should be available in the next version but we need to make sure that we can enable it.

**Comment by iLabsJason** [comment]
@cyrille-socket Thanks for your reply!

**Comment by cyrille-socket** [comment]
Hi @iLabsJason the new version 1.5.5 of the CaptureSDK is out and Bitcode is enabled.
Let me know if it works so I can close this issue

**Comment by iLabsJason** [comment]
@cyrille-socket Cool, thank you!
