### ISSUE TITLE
Test Flight downloaded app does not seem to work with the scanner

### ISSUE THREAD

**Issue by tomcondon** [SocketMobile/swift-package-capturesdk#4]
This is a very odd one. I updated to the latest library (Capture version 1.5.2.676) and my scanning code works fine when I run it from Xcode. However, when I uploaded it to TestFlight and then downloaded it to my device with a properly paired S700 scanner, the scanner code seems to fail silently.

Any ideas of what is happening?

M1 iPadAir
iPadOS 15.6.1
Xcode 13.4.1

**Comment by tomcondon** [comment]
FYI: converting back to the latest CocoaPods version of this library seems to work fine. I think you have issues with your SPM library.

**Comment by cyrille-socket** [comment]
Hi @tomcondon . Do you have any error code or something?
Does the scanner connect to your app?
Does the scanner beeps?
Do you manage to scan barcodes?
Also, the latest version is 1.5.5 if you can try. We have enabled Bitcode.

**Comment by cyrille-socket** [comment]
No more activity on this thread since more than 1 year.
